# syntax=docker/dockerfile:1.7-labs

# This Dockerfile is used to check that the project currently builds on our target machine.
# Therefore, the versions of the nix channel is set to a fixed versions.

FROM nixos/nix:latest
WORKDIR /tmp/k4status
RUN nix-channel --remove nixpkgs &&\
    nix-channel --add https://nixos.org/channels/nixos-25.11 nixpkgs &&\
    nix-channel --update
COPY --exclude=target/ . .
RUN nix-build default.nix
CMD ["bash"]