# syntax=docker/dockerfile:1.7-labs

# This Dockerfile is used to check that the project currently builds on our target machine.
# Therefore, the versions of the nix docker image and the nix channel are set to fixed versions.

FROM nixos/nix:2.28.3
WORKDIR /tmp/k4status
RUN nix-channel --remove nixpkgs &&\
    nix-channel --add https://nixos.org/channels/nixos-25.05 nixpkgs &&\
    nix-channel --update
COPY --exclude=target/ . .
RUN nix-build default.nix
CMD ["bash"]