name: Test

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install prerequisites
      run: sudo apt-get update && sudo apt-get install -y jq libxml2-utils cargo rust-clippy rustfmt
    - name: Run build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all-targets
    - name: Check file formatting
      run: |
        bash format.sh
        git diff --exit-code