name: Test

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all-targets
    - name: Check json format
      run: |
        sudo apt-get install -y jq
        bash format_json.sh
        git diff --exit-code