name: Test

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prerequisites
      run: |
        sudo apt install -y musl-tools musl-dev
        rustup target add x86_64-unknown-linux-musl
    - name: Run build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all-targets
